GET http://localhost:1336/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM2MjM5ODMyLCJleHAiOjE3Mzg4MzE4MzJ9.MKiPfnuPp2gUhkreoOhVxANF8ivzEL_6SEFIols_nFk
Content-Type: application/json


